version: '3'
services:
  db:
    ports:
      - "5433:5432"
    container_name: postgres_container
    image: postgres:16.0
    environment:
      - POSTGRES_DB=WF
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    volumes:
      - ./data:/var/lib/postgresql/data
    restart: always

  backend:
    build: ./Backend/WorldFitBackend
    container_name: worldfit_backend_container
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://db:5432/WF
      DB_USERNAME: postgres
      DB_PASSWORD: admin
    volumes:
      - ./statics/images:/var/lib/images
    depends_on:
      - db
    restart: always

  frontend:
    build:
      context: ./FrontEnd
      dockerfile: Dockerfile
    container_name: worldfit_frontend_container
    ports:
      - "4200:4200"
    environment:
      - NODE_ENV=development  # Modo de desarrollo
    restart: always
    depends_on:
      - backend
